# Form implementation generated from reading ui file 'untitled_post.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_Post(object):
    def setupUi(self, MainWindow_Post):
        MainWindow_Post.setObjectName("MainWindow_Post")
        MainWindow_Post.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow_Post)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_post_start = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_post_start.setGeometry(QtCore.QRect(80, 220, 75, 23))
        self.pushButton_post_start.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_post_start.setStyleSheet("QPushButton {\n"
"border:2px solid rgb(0, 0, 0);\n"
"border-radius: 5px;\n"
"background-color: rgb(0, 0, 0, 0);\n"
"}")
        self.pushButton_post_start.setObjectName("pushButton_post_start")
        self.pushButton_download_template = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_download_template.setGeometry(QtCore.QRect(690, 40, 75, 23))
        self.pushButton_download_template.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_download_template.setStyleSheet("QPushButton {\n"
"border:2px solid rgb(0, 0, 0);\n"
"border-radius: 5px;\n"
"background-color: rgb(0, 0, 0, 0);\n"
"}")
        self.pushButton_download_template.setObjectName("pushButton_download_template")
        self.tableWidget_preview = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget_preview.setGeometry(QtCore.QRect(30, 340, 751, 192))
        self.tableWidget_preview.setRowCount(0)
        self.tableWidget_preview.setColumnCount(9)
        self.tableWidget_preview.setObjectName("tableWidget_preview")
        self.tableWidget_preview.horizontalHeader().setDefaultSectionSize(82)
        self.pushButton_post_preview = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_post_preview.setGeometry(QtCore.QRect(690, 270, 75, 23))
        self.pushButton_post_preview.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_post_preview.setStyleSheet("QPushButton {\n"
"border:2px solid rgb(0, 0, 0);\n"
"border-radius: 5px;\n"
"background-color: rgb(0, 0, 0, 0);\n"
"}")
        self.pushButton_post_preview.setObjectName("pushButton_post_preview")
        self.pushButton_edit_template = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_edit_template.setGeometry(QtCore.QRect(690, 70, 75, 23))
        self.pushButton_edit_template.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_edit_template.setStyleSheet("QPushButton {\n"
"border:2px solid rgb(0, 0, 0);\n"
"border-radius: 5px;\n"
"background-color: rgb(0, 0, 0, 0);\n"
"}")
        self.pushButton_edit_template.setObjectName("pushButton_edit_template")
        MainWindow_Post.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow_Post)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow_Post.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow_Post)
        self.statusbar.setObjectName("statusbar")
        MainWindow_Post.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow_Post)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_Post)

    def retranslateUi(self, MainWindow_Post):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_Post.setWindowTitle(_translate("MainWindow_Post", "MainWindow"))
        self.pushButton_post_start.setText(_translate("MainWindow_Post", "开始执行"))
        self.pushButton_download_template.setText(_translate("MainWindow_Post", "下载模板"))
        self.pushButton_post_preview.setText(_translate("MainWindow_Post", "预览数据"))
        self.pushButton_edit_template.setText(_translate("MainWindow_Post", "编辑模板"))
