# Form implementation generated from reading ui file 'untitled_setting.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form_setting(object):
    def setupUi(self, Form_setting):
        Form_setting.setObjectName("Form_setting")
        Form_setting.setWindowModality(QtCore.Qt.WindowModality.NonModal)
        Form_setting.resize(400, 300)
        self.frame = QtWidgets.QFrame(parent=Form_setting)
        self.frame.setGeometry(QtCore.QRect(80, 100, 271, 91))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(0, 30, 71, 21))
        self.label.setObjectName("label")
        self.pushButton_normal_mode = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_normal_mode.setGeometry(QtCore.QRect(70, 30, 91, 23))
        self.pushButton_normal_mode.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_normal_mode.setStyleSheet("QPushButton {\n"
"border:2px solid rgb(0, 0, 0);\n"
"border-radius: 5px;\n"
"background-color: rgb(0, 0, 0, 0);\n"
"}")
        self.pushButton_normal_mode.setObjectName("pushButton_normal_mode")
        self.pushButton_incognito_mode = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_incognito_mode.setGeometry(QtCore.QRect(170, 30, 91, 23))
        self.pushButton_incognito_mode.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_incognito_mode.setStyleSheet("QPushButton {\n"
"border:2px solid rgb(0, 0, 0);\n"
"border-radius: 5px;\n"
"background-color: rgb(0, 0, 0, 0);\n"
"}")
        self.pushButton_incognito_mode.setObjectName("pushButton_incognito_mode")

        self.retranslateUi(Form_setting)
        QtCore.QMetaObject.connectSlotsByName(Form_setting)

    def retranslateUi(self, Form_setting):
        _translate = QtCore.QCoreApplication.translate
        Form_setting.setWindowTitle(_translate("Form_setting", "参数设置"))
        self.label.setText(_translate("Form_setting", "浏览器模式："))
        self.pushButton_normal_mode.setText(_translate("Form_setting", "启动正常模式"))
        self.pushButton_incognito_mode.setText(_translate("Form_setting", "启动无痕模式"))
