# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModality.NonModal)
        MainWindow.resize(987, 754)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        MainWindow.setToolTip("")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_start = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_start.setGeometry(QtCore.QRect(70, 380, 75, 23))
        self.pushButton_start.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_start.setStyleSheet("QPushButton {\n"
"border:2px solid rgb(0, 0, 0);\n"
"border-radius: 5px;\n"
"background-color: rgb(0, 0, 0, 0);\n"
"}")
        self.pushButton_start.setObjectName("pushButton_start")
        self.textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(70, 450, 821, 200))
        self.textEdit.setStyleSheet("QTextEdit {\n"
"border:2px solid rgb(0, 0, 0);\n"
"border-radius: 10px;\n"
"background-color: rgb(0, 0, 0, 0);\n"
"}")
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 420, 54, 12))
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.pushButton_pause = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_pause.setGeometry(QtCore.QRect(200, 380, 75, 23))
        self.pushButton_pause.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_pause.setStyleSheet("QPushButton {\n"
"border:2px solid rgb(0, 0, 0);\n"
"border-radius: 5px;\n"
"background-color: rgb(0, 0, 0, 0);\n"
"}")
        self.pushButton_pause.setObjectName("pushButton_pause")
        self.pushButton_resume = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_resume.setGeometry(QtCore.QRect(330, 380, 75, 23))
        self.pushButton_resume.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_resume.setStyleSheet("QPushButton {\n"
"border:2px solid rgb(0, 0, 0);\n"
"border-radius: 5px;\n"
"background-color: rgb(0, 0, 0, 0);\n"
"}")
        self.pushButton_resume.setObjectName("pushButton_resume")
        self.pushButton_end = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_end.setGeometry(QtCore.QRect(460, 380, 75, 23))
        self.pushButton_end.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_end.setStyleSheet("QPushButton {\n"
"border:2px solid rgb(0, 0, 0);\n"
"border-radius: 5px;\n"
"background-color: rgb(0, 0, 0, 0);\n"
"}")
        self.pushButton_end.setObjectName("pushButton_end")
        self.pushButton_edit_template = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_edit_template.setGeometry(QtCore.QRect(850, 100, 75, 23))
        self.pushButton_edit_template.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_edit_template.setStyleSheet("QPushButton {\n"
"border:2px solid rgb(0, 0, 0);\n"
"border-radius: 5px;\n"
"background-color: rgb(0, 0, 0, 0);\n"
"}")
        self.pushButton_edit_template.setObjectName("pushButton_edit_template")
        self.pushButton_download_template = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_download_template.setGeometry(QtCore.QRect(850, 70, 75, 23))
        self.pushButton_download_template.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_download_template.setStyleSheet("QPushButton {\n"
"border:2px solid rgb(0, 0, 0);\n"
"border-radius: 5px;\n"
"background-color: rgb(0, 0, 0, 0);\n"
"}")
        self.pushButton_download_template.setObjectName("pushButton_download_template")
        self.frame_box = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_box.setGeometry(QtCore.QRect(60, 60, 761, 300))
        self.frame_box.setStyleSheet("")
        self.frame_box.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_box.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_box.setObjectName("frame_box")
        self.pushButton_edit_attachment = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_edit_attachment.setGeometry(QtCore.QRect(850, 130, 75, 23))
        self.pushButton_edit_attachment.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_edit_attachment.setStyleSheet("QPushButton {\n"
"border:2px solid rgb(0, 0, 0);\n"
"border-radius: 5px;\n"
"background-color: rgb(0, 0, 0, 0);\n"
"}")
        self.pushButton_edit_attachment.setObjectName("pushButton_edit_attachment")
        self.frame_report = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_report.setGeometry(QtCore.QRect(590, 380, 221, 41))
        self.frame_report.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_report.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_report.setObjectName("frame_report")
        self.pushButton_report = QtWidgets.QPushButton(parent=self.frame_report)
        self.pushButton_report.setGeometry(QtCore.QRect(0, 0, 75, 23))
        self.pushButton_report.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_report.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.pushButton_report.setStyleSheet("QPushButton {\n"
"border:2px solid rgb(0, 0, 0);\n"
"border-radius: 5px;\n"
"background-color: rgb(0, 0, 0, 0);\n"
"}")
        self.pushButton_report.setObjectName("pushButton_report")
        self.label_report_text = QtWidgets.QLabel(parent=self.frame_report)
        self.label_report_text.setGeometry(QtCore.QRect(0, 20, 71, 20))
        self.label_report_text.setObjectName("label_report_text")
        self.toolButton_report = QtWidgets.QToolButton(parent=self.frame_report)
        self.toolButton_report.setGeometry(QtCore.QRect(200, 20, 21, 18))
        self.toolButton_report.setObjectName("toolButton_report")
        self.lineEdit_report = QtWidgets.QLineEdit(parent=self.frame_report)
        self.lineEdit_report.setGeometry(QtCore.QRect(70, 20, 131, 20))
        self.lineEdit_report.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.lineEdit_report.setToolTip("")
        self.lineEdit_report.setStyleSheet("QLineEdit {\n"
"\n"
"border:0px solid rgb(0, 0, 0);\n"
"background-color: rgb(0, 0, 0, 0);\n"
"}\n"
"")
        self.lineEdit_report.setText("")
        self.lineEdit_report.setObjectName("lineEdit_report")
        self.pushButton_clear_text = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_clear_text.setGeometry(QtCore.QRect(900, 450, 75, 23))
        self.pushButton_clear_text.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_clear_text.setStyleSheet("QPushButton {\n"
"border:2px solid rgb(0, 0, 0);\n"
"border-radius: 5px;\n"
"background-color: rgb(0, 0, 0, 0);\n"
"}")
        self.pushButton_clear_text.setObjectName("pushButton_clear_text")
        self.pushButton_parameter_setting = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_parameter_setting.setGeometry(QtCore.QRect(850, 240, 75, 23))
        self.pushButton_parameter_setting.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_parameter_setting.setStyleSheet("QPushButton {\n"
"border:2px solid rgb(0, 0, 0);\n"
"border-radius: 5px;\n"
"background-color: rgb(0, 0, 0, 0);\n"
"}")
        self.pushButton_parameter_setting.setObjectName("pushButton_parameter_setting")
        self.pushButton_logging = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_logging.setGeometry(QtCore.QRect(900, 380, 75, 23))
        self.pushButton_logging.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_logging.setStyleSheet("QPushButton {\n"
"border:2px solid rgb(0, 0, 0);\n"
"border-radius: 5px;\n"
"background-color: rgb(0, 0, 0, 0);\n"
"}")
        self.pushButton_logging.setObjectName("pushButton_logging")
        self.pushButton_export = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_export.setGeometry(QtCore.QRect(660, 20, 75, 23))
        self.pushButton_export.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_export.setStyleSheet("QPushButton {\n"
"border:2px solid rgb(0, 0, 0);\n"
"border-radius: 5px;\n"
"background-color: rgb(0, 0, 0, 0);\n"
"}")
        self.pushButton_export.setObjectName("pushButton_export")
        self.pushButton_import = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_import.setGeometry(QtCore.QRect(750, 20, 75, 23))
        self.pushButton_import.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_import.setStyleSheet("QPushButton {\n"
"border:2px solid rgb(0, 0, 0);\n"
"border-radius: 5px;\n"
"background-color: rgb(0, 0, 0, 0);\n"
"}")
        self.pushButton_import.setObjectName("pushButton_import")
        self.pushButton_post = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_post.setGeometry(QtCore.QRect(60, 10, 75, 23))
        self.pushButton_post.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_post.setStyleSheet("QPushButton {\n"
"border:2px solid rgb(0, 0, 0);\n"
"border-radius: 5px;\n"
"background-color: rgb(0, 0, 0, 0);\n"
"}")
        self.pushButton_post.setObjectName("pushButton_post")
        self.frame_report.raise_()
        self.frame_box.raise_()
        self.pushButton_start.raise_()
        self.textEdit.raise_()
        self.label.raise_()
        self.pushButton_pause.raise_()
        self.pushButton_resume.raise_()
        self.pushButton_end.raise_()
        self.pushButton_edit_template.raise_()
        self.pushButton_download_template.raise_()
        self.pushButton_edit_attachment.raise_()
        self.pushButton_clear_text.raise_()
        self.pushButton_parameter_setting.raise_()
        self.pushButton_logging.raise_()
        self.pushButton_export.raise_()
        self.pushButton_import.raise_()
        self.pushButton_post.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 987, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.pushButton_pause, self.pushButton_edit_attachment)
        MainWindow.setTabOrder(self.pushButton_edit_attachment, self.textEdit)
        MainWindow.setTabOrder(self.textEdit, self.pushButton_start)
        MainWindow.setTabOrder(self.pushButton_start, self.pushButton_resume)
        MainWindow.setTabOrder(self.pushButton_resume, self.pushButton_download_template)
        MainWindow.setTabOrder(self.pushButton_download_template, self.pushButton_edit_template)
        MainWindow.setTabOrder(self.pushButton_edit_template, self.pushButton_end)
        MainWindow.setTabOrder(self.pushButton_end, self.pushButton_report)
        MainWindow.setTabOrder(self.pushButton_report, self.toolButton_report)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "UI自动化"))
        self.pushButton_start.setText(_translate("MainWindow", "开始执行"))
        self.label.setText(_translate("MainWindow", "执行结果"))
        self.pushButton_pause.setText(_translate("MainWindow", "暂停执行"))
        self.pushButton_resume.setText(_translate("MainWindow", "继续执行"))
        self.pushButton_end.setText(_translate("MainWindow", "结束执行"))
        self.pushButton_edit_template.setText(_translate("MainWindow", "编辑模板"))
        self.pushButton_download_template.setText(_translate("MainWindow", "下载模板"))
        self.pushButton_edit_attachment.setText(_translate("MainWindow", "编辑附件"))
        self.pushButton_report.setText(_translate("MainWindow", "启用报告"))
        self.label_report_text.setText(_translate("MainWindow", "  存储地址："))
        self.toolButton_report.setText(_translate("MainWindow", "..."))
        self.pushButton_clear_text.setText(_translate("MainWindow", "清空文本"))
        self.pushButton_parameter_setting.setText(_translate("MainWindow", "参数设置"))
        self.pushButton_logging.setText(_translate("MainWindow", "启动日志"))
        self.pushButton_export.setText(_translate("MainWindow", "导出"))
        self.pushButton_import.setText(_translate("MainWindow", "导入"))
        self.pushButton_post.setText(_translate("MainWindow", "接口测试"))
