# Form implementation generated from reading ui file 'untitled_template.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form_Template(object):
    def setupUi(self, Form_Template):
        Form_Template.setObjectName("Form_Template")
        Form_Template.resize(370, 560)
        self.frame_Edit_Template = QtWidgets.QFrame(parent=Form_Template)
        self.frame_Edit_Template.setGeometry(QtCore.QRect(10, 10, 351, 541))
        self.frame_Edit_Template.setStyleSheet("QFrame\n"
"{\n"
"border:2px solid rgb(0, 0, 0);\n"
"border-radius: 5px;\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.frame_Edit_Template.setFrameShape(QtWidgets.QFrame.Shape.Panel)
        self.frame_Edit_Template.setLineWidth(3)
        self.frame_Edit_Template.setObjectName("frame_Edit_Template")
        self.listWidget_original = QtWidgets.QListWidget(parent=self.frame_Edit_Template)
        self.listWidget_original.setGeometry(QtCore.QRect(10, 60, 256, 192))
        self.listWidget_original.setStyleSheet("QListWidget\n"
"{\n"
"border:2px solid rgb(0, 0, 0);\n"
"border-radius: 5px;\n"
"background-color: rgb(0, 0, 0, 0);\n"
"}")
        self.listWidget_original.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.ExtendedSelection)
        self.listWidget_original.setObjectName("listWidget_original")
        self.label_2 = QtWidgets.QLabel(parent=self.frame_Edit_Template)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 81, 21))
        self.label_2.setStyleSheet("QLabel\n"
"{\n"
"border: none;\n"
"border-radius: 5px;\n"
"background-color: rgb(0, 0, 0, 0);\n"
"}")
        self.label_2.setObjectName("label_2")
        self.pushButton_original_append = QtWidgets.QPushButton(parent=self.frame_Edit_Template)
        self.pushButton_original_append.setGeometry(QtCore.QRect(270, 60, 75, 23))
        self.pushButton_original_append.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_original_append.setStyleSheet("QPushButton {\n"
"border:2px solid rgb(0, 0, 0);\n"
"border-radius: 5px;\n"
"background-color: rgb(0, 0, 0, 0);\n"
"}")
        self.pushButton_original_append.setObjectName("pushButton_original_append")
        self.pushButton_original_delete = QtWidgets.QPushButton(parent=self.frame_Edit_Template)
        self.pushButton_original_delete.setGeometry(QtCore.QRect(270, 90, 75, 23))
        self.pushButton_original_delete.setStyleSheet("QPushButton {\n"
"border:2px solid rgb(0, 0, 0);\n"
"border-radius: 5px;\n"
"background-color: rgb(0, 0, 0, 0);\n"
"}")
        self.pushButton_original_delete.setObjectName("pushButton_original_delete")
        self.listWidget_replace = QtWidgets.QListWidget(parent=self.frame_Edit_Template)
        self.listWidget_replace.setGeometry(QtCore.QRect(10, 300, 256, 192))
        self.listWidget_replace.setStyleSheet("QListWidget\n"
"{\n"
"border:2px solid rgb(0, 0, 0);\n"
"border-radius: 5px;\n"
"background-color: rgb(0, 0, 0, 0);\n"
"}")
        self.listWidget_replace.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.ExtendedSelection)
        self.listWidget_replace.setObjectName("listWidget_replace")
        self.pushButton_replace_append = QtWidgets.QPushButton(parent=self.frame_Edit_Template)
        self.pushButton_replace_append.setGeometry(QtCore.QRect(270, 300, 75, 23))
        self.pushButton_replace_append.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_replace_append.setStyleSheet("QPushButton {\n"
"border:2px solid rgb(0, 0, 0);\n"
"border-radius: 5px;\n"
"background-color: rgb(0, 0, 0, 0);\n"
"}")
        self.pushButton_replace_append.setObjectName("pushButton_replace_append")
        self.label_3 = QtWidgets.QLabel(parent=self.frame_Edit_Template)
        self.label_3.setGeometry(QtCore.QRect(10, 280, 81, 21))
        self.label_3.setStyleSheet("QLabel\n"
"{\n"
"border: none;\n"
"border-radius: 5px;\n"
"background-color: rgb(0, 0, 0, 0);\n"
"}")
        self.label_3.setObjectName("label_3")
        self.pushButton_replace_delete = QtWidgets.QPushButton(parent=self.frame_Edit_Template)
        self.pushButton_replace_delete.setGeometry(QtCore.QRect(270, 330, 75, 23))
        self.pushButton_replace_delete.setStyleSheet("QPushButton {\n"
"border:2px solid rgb(0, 0, 0);\n"
"border-radius: 5px;\n"
"background-color: rgb(0, 0, 0, 0);\n"
"}")
        self.pushButton_replace_delete.setObjectName("pushButton_replace_delete")
        self.label_4 = QtWidgets.QLabel(parent=self.frame_Edit_Template)
        self.label_4.setGeometry(QtCore.QRect(0, 0, 81, 21))
        self.label_4.setStyleSheet("QLabel\n"
"{\n"
"border: none;\n"
"border-radius: 5px;\n"
"background-color: rgb(0, 0, 0, 0);\n"
"}")
        self.label_4.setObjectName("label_4")
        self.pushButton_template_confirm = QtWidgets.QPushButton(parent=self.frame_Edit_Template)
        self.pushButton_template_confirm.setGeometry(QtCore.QRect(60, 510, 75, 23))
        self.pushButton_template_confirm.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_template_confirm.setStyleSheet("QPushButton {\n"
"border:2px solid rgb(0, 0, 0);\n"
"border-radius: 5px;\n"
"background-color: rgb(0, 0, 0, 0);\n"
"}")
        self.pushButton_template_confirm.setObjectName("pushButton_template_confirm")
        self.pushButton_template_cancel = QtWidgets.QPushButton(parent=self.frame_Edit_Template)
        self.pushButton_template_cancel.setGeometry(QtCore.QRect(190, 510, 75, 23))
        self.pushButton_template_cancel.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_template_cancel.setStyleSheet("QPushButton {\n"
"border:2px solid rgb(0, 0, 0);\n"
"border-radius: 5px;\n"
"background-color: rgb(0, 0, 0, 0);\n"
"}")
        self.pushButton_template_cancel.setObjectName("pushButton_template_cancel")

        self.retranslateUi(Form_Template)
        self.listWidget_original.setCurrentRow(-1)
        self.listWidget_replace.setCurrentRow(-1)
        QtCore.QMetaObject.connectSlotsByName(Form_Template)

    def retranslateUi(self, Form_Template):
        _translate = QtCore.QCoreApplication.translate
        Form_Template.setWindowTitle(_translate("Form_Template", "编辑模板"))
        self.listWidget_original.setSortingEnabled(False)
        self.label_2.setText(_translate("Form_Template", " 原始导入模板"))
        self.pushButton_original_append.setText(_translate("Form_Template", "新增"))
        self.pushButton_original_delete.setText(_translate("Form_Template", "删除"))
        self.pushButton_replace_append.setText(_translate("Form_Template", "新增"))
        self.label_3.setText(_translate("Form_Template", " 替换导入模板"))
        self.pushButton_replace_delete.setText(_translate("Form_Template", "删除"))
        self.label_4.setText(_translate("Form_Template", " 编辑模板"))
        self.pushButton_template_confirm.setText(_translate("Form_Template", "确认"))
        self.pushButton_template_cancel.setText(_translate("Form_Template", "取消"))
