# Form implementation generated from reading ui file 'untitled_logging.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_logging(object):
    def setupUi(self, MainWindow_logging):
        MainWindow_logging.setObjectName("MainWindow_logging")
        MainWindow_logging.resize(750, 500)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow_logging)
        self.centralwidget.setMinimumSize(QtCore.QSize(300, 300))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit_logging = QtWidgets.QLineEdit(parent=self.widget_2)
        self.lineEdit_logging.setStyleSheet("QLineEdit {\n"
"border: rgb(200, 200, 200, 0);\n"
"background-color: rgb(200, 200, 200, 0);\n"
"}")
        self.lineEdit_logging.setReadOnly(True)
        self.lineEdit_logging.setObjectName("lineEdit_logging")
        self.verticalLayout.addWidget(self.lineEdit_logging)
        self.textEdit_logging = QtWidgets.QTextEdit(parent=self.widget_2)
        self.textEdit_logging.setStyleSheet("QTextEdit {\n"
"border:2px solid rgb(0, 0, 0);\n"
"border-radius: 10px;\n"
"background-color: rgb(200, 200, 200, 0);\n"
"}")
        self.textEdit_logging.setReadOnly(True)
        self.textEdit_logging.setObjectName("textEdit_logging")
        self.verticalLayout.addWidget(self.textEdit_logging)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(552, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pushButton_logging_close = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_logging_close.setMinimumSize(QtCore.QSize(0, 23))
        self.pushButton_logging_close.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_logging_close.setStyleSheet("QPushButton {\n"
"border:2px solid rgb(0, 0, 0);\n"
"border-radius: 5px;\n"
"background-color: rgb(0, 0, 0, 0);\n"
"}")
        self.pushButton_logging_close.setObjectName("pushButton_logging_close")
        self.horizontalLayout_2.addWidget(self.pushButton_logging_close)
        self.pushButton_logging_clear = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_logging_clear.setMinimumSize(QtCore.QSize(0, 23))
        self.pushButton_logging_clear.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_logging_clear.setStyleSheet("QPushButton {\n"
"border:2px solid rgb(0, 0, 0);\n"
"border-radius: 5px;\n"
"background-color: rgb(0, 0, 0, 0);\n"
"}")
        self.pushButton_logging_clear.setObjectName("pushButton_logging_clear")
        self.horizontalLayout_2.addWidget(self.pushButton_logging_clear)
        self.verticalLayout_2.addWidget(self.widget)
        MainWindow_logging.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow_logging)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_logging)

    def retranslateUi(self, MainWindow_logging):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_logging.setWindowTitle(_translate("MainWindow_logging", "报错日志"))
        self.lineEdit_logging.setText(_translate("MainWindow_logging", "报错日志"))
        self.textEdit_logging.setHtml(_translate("MainWindow_logging", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.pushButton_logging_close.setText(_translate("MainWindow_logging", "关闭窗口"))
        self.pushButton_logging_clear.setText(_translate("MainWindow_logging", "清除文本"))
